import streamlit as st
import requests
from weasyprint import HTML

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="UK History Researcher",
    page_icon="🇬🇧",
    layout="centered"
)

# --- API SETUP (Hugging Face) ---
# We use Mistral-7B, which is excellent at summaries.
API_URL = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2"

try:
    if "HF_TOKEN" in st.secrets:
        headers = {"Authorization": f"Bearer {st.secrets['HF_TOKEN']}"}
    else:
        st.error("Admin Note: Please add HF_TOKEN to your Streamlit Secrets.")
        st.stop()
except Exception as e:
    st.error(f"Configuration Error: {e}")
    st.stop()

def query_ai(prompt):
    payload = {
        "inputs": f"<s>[INST] {prompt} [/INST]",
        "parameters": {"max_new_tokens": 1000, "return_full_text": False}
    }
    response = requests.post(API_URL, headers=headers, json=payload)
    # The API might be 'loading' the model, so we handle that
    result = response.json()
    if isinstance(result, dict) and "error" in result:
        if "loading" in result["error"]:
            return "Model is starting up... please wait 30 seconds and try again."
        return f"AI Error: {result['error']}"
    return result[0]['generated_text']

# --- PDF GENERATION FUNCTION ---
def create_pdf(text, year):
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Helvetica', sans-serif; padding: 20px; color: #333; }}
            h1 {{ color: #00247d; border-bottom: 2px solid #cf142b; }}
            .disclaimer {{ font-size: 0.7em; color: #666; margin-top: 40px; border-top: 1px solid #eee; }}
        </style>
    </head>
    <body>
        <h1>UK History Report: {year}</h1>
        <div>{text.replace('\n', '<br>')}</div>
        <div class="disclaimer">Disclaimer: Generated by AI. Historical accuracy is not guaranteed.</div>
    </body>
    </html>
    """
    return HTML(string=html_content).write_pdf()

# --- USER INTERFACE ---
st.title("🇬🇧 UK Year Researcher")
st.write("Enter a year to receive a summary of UK historical events (Powered by Hugging Face).")

target_year = st.number_input("Year to Research:", min_value=1, max_value=2026, value=2024)
st.caption("⚠️ **Disclaimer:** Information is generated by AI. Verify facts with primary sources.")

if st.button("Give Info"):
    with st.spinner(f"Querying Mistral AI for {target_year}..."):
        prompt = f"""Summarize the major historical events in the United Kingdom during the year {target_year}. 
        Focus on:
        1. Political changes or elections.
        2. Social and cultural milestones.
        3. Economy.
        4. Provide a 'Sources' list of credible references for these events."""
        
        answer = query_ai(prompt)
        st.session_state['summary_text'] = answer
        st.session_state['searched_year'] = target_year

# --- DISPLAY & DOWNLOAD ---
if 'summary_text' in st.session_state:
    st.markdown("---")
    st.markdown(st.session_state['summary_text'])
    
    if "Error" not in st.session_state['summary_text'] and "starting up" not in st.session_state['summary_text']:
        pdf_bytes = create_pdf(st.session_state['summary_text'], st.session_state['searched_year'])
        st.download_button(
            label="📥 Download Research as PDF",
            data=pdf_bytes,
            file_name=f"UK_History_{st.session_state['searched_year']}.pdf",
            mime="application/pdf"
        )