import streamlit as st
import google.generativeai as genai
from weasyprint import HTML
import base64

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="UK History Researcher",
    page_icon="🇬🇧",
    layout="centered"
)

# --- API SETUP (Using Secrets) ---
# This looks for your key in the Streamlit Dashboard settings
try:
    if "GEMINI_API_KEY" in st.secrets:
        genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
        model = genai.GenerativeModel('gemini-1.5-flash')
    else:
        st.error("Admin Note: Please add GEMINI_API_KEY to your Streamlit Secrets.")
        st.stop()
except Exception as e:
    st.error(f"Configuration Error: {e}")
    st.stop()

# --- PDF GENERATION FUNCTION ---
def create_pdf(text, year):
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Helvetica', sans-serif; padding: 20px; color: #333; }}
            h1 {{ color: #00247d; border-bottom: 2px solid #cf142b; }}
            h2 {{ color: #00247d; }}
            .disclaimer {{ font-size: 0.7em; color: #666; margin-top: 40px; border-top: 1px solid #eee; }}
        </style>
    </head>
    <body>
        <h1>UK History Report: {year}</h1>
        <div>{text.replace('\n', '<br>')}</div>
        <div class="disclaimer">
            Disclaimer: This summary is AI-generated for informational purposes. 
            Historical accuracy is not guaranteed.
        </div>
    </body>
    </html>
    """
    return HTML(string=html_content).write_pdf()

# --- USER INTERFACE ---
st.title("🇬🇧 UK Year Researcher")
st.write("Enter a year to receive an AI-powered summary of events in the United Kingdom.")

# Input
target_year = st.number_input("Year to Research:", min_value=1, max_value=2026, value=2024)

# Disclaimer in UI
st.caption("⚠️ **Disclaimer:** Information is generated by AI. Please verify important historical facts with primary sources.")

if st.button("Give Info"):
    with st.spinner(f"Searching archives for {target_year}..."):
        try:
            prompt = f"""
            Provide a detailed summary of the United Kingdom in the year {target_year}.
            Structure the response clearly with:
            - Major Political Events
            - Social and Cultural Milestones
            - Economic Overview
            - A 'Sources' section listing credible historical references or news archives.
            """
            response = model.generate_content(prompt)
            
            # Save results to session state so they persist for the download button
            st.session_state['summary_text'] = response.text
            st.session_state['searched_year'] = target_year

        except Exception as e:
            st.error(f"AI Error: {e}")

# --- DISPLAY RESULTS & DOWNLOAD ---
if 'summary_text' in st.session_state:
    st.markdown("---")
    st.markdown(st.session_state['summary_text'])
    
    # Generate PDF
    pdf_bytes = create_pdf(st.session_state['summary_text'], st.session_state['searched_year'])
    
    st.download_button(
        label="📥 Download Research as PDF",
        data=pdf_bytes,
        file_name=f"UK_History_{st.session_state['searched_year']}.pdf",
        mime="application/pdf"
    )