import streamlit as st
import requests
from fpdf import FPDF

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="UK History Researcher",
    page_icon="🇬🇧",
    layout="centered"
)

# --- API SETUP (Hugging Face) ---
API_URL = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2"

try:
    if "HF_TOKEN" in st.secrets:
        headers = {"Authorization": f"Bearer {st.secrets['HF_TOKEN']}"}
    else:
        st.error("Admin Note: Please add HF_TOKEN to your Streamlit Secrets.")
        st.stop()
except Exception as e:
    st.error(f"Configuration Error: {e}")
    st.stop()

def query_ai(prompt):
    payload = {
        "inputs": f"<s>[INST] {prompt} [/INST]",
        "parameters": {"max_new_tokens": 1200, "return_full_text": False}
    }
    response = requests.post(API_URL, headers=headers, json=payload)
    result = response.json()
    
    if isinstance(result, dict) and "error" in result:
        if "loading" in result["error"]:
            return "Model is starting up... please wait 30 seconds and click 'Give Info' again."
        return f"AI Error: {result['error']}"
    
    return result[0]['generated_text']

# --- NEW PDF GENERATION FUNCTION (FPDF2) ---
def create_pdf(text, year):
    pdf = FPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, f"UK Historical Summary: {year}", ln=True, align='C')
    pdf.ln(10)
    
    # Body
    pdf.set_font("Helvetica", size=12)
    # We use multi_cell to handle text wrapping and encode for standard Latin-1
    pdf.multi_cell(0, 10, text.encode('latin-1', 'ignore').decode('latin-1'))
    
    # Disclaimer
    pdf.ln(20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 5, "Disclaimer: Generated by AI. Historical accuracy is not guaranteed.")
    
    return pdf.output()

# --- USER INTERFACE ---
st.title("🇬🇧 UK Year Researcher")
st.write("Enter a year to receive a summary of UK historical events.")

target_year = st.number_input("Year to Research:", min_value=1, max_value=2026, value=2024)
st.caption("⚠️ **Disclaimer:** Information is generated by AI. Verify facts with primary sources.")

if st.button("Give Info"):
    with st.spinner(f"Querying AI for {target_year}..."):
        prompt = f"Provide a detailed summary of the United Kingdom in {target_year}. Include Political, Social, and Economic sections with sources."
        answer = query_ai(prompt)
        st.session_state['summary_text'] = answer
        st.session_state['searched_year'] = target_year

# --- DISPLAY & DOWNLOAD ---
if 'summary_text' in st.session_state:
    st.markdown("---")
    st.markdown(st.session_state['summary_text'])
    
    # Check if we got a real response before showing download
    if "Error" not in st.session_state['summary_text'] and "starting up" not in st.session_state['summary_text']:
        pdf_output = create_pdf(st.session_state['summary_text'], st.session_state['searched_year'])
        
        st.download_button(
            label="📥 Download Research as PDF",
            data=bytes(pdf_output),
            file_name=f"UK_History_{st.session_state['searched_year']}.pdf",
            mime="application/pdf"
        )