import streamlit as st
import requests
from fpdf import FPDF
import time

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="UK History Researcher",
    page_icon="🇬🇧",
    layout="centered"
)

# --- API SETUP ---
# Switching to Llama-3-8B as it is often more stable on the free API
API_URL = "https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-8B-Instruct"

try:
    if "HF_TOKEN" in st.secrets:
        headers = {"Authorization": f"Bearer {st.secrets['HF_TOKEN']}"}
    else:
        st.error("Admin Note: Please add HF_TOKEN to your Streamlit Secrets.")
        st.stop()
except Exception as e:
    st.error(f"Configuration Error: {e}")
    st.stop()

def query_ai(prompt):
    payload = {
        "inputs": f"<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\n{prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n",
        "parameters": {"max_new_tokens": 800, "temperature": 0.7}
    }
    
    try:
        response = requests.post(API_URL, headers=headers, json=payload, timeout=20)
        
        # Check if the API returned an error code (like 503 or 404)
        if response.status_code != 200:
            return f"Error: The AI server is busy (Status {response.status_code}). Please wait 10 seconds and try again."
        
        result = response.json()
        
        if isinstance(result, dict) and "error" in result:
            if "loading" in result["error"]:
                return "The AI is currently 'waking up'. Please wait 30 seconds and click 'Give Info' again."
            return f"AI Error: {result['error']}"
            
        return result[0]['generated_text']
        
    except requests.exceptions.JSONDecodeError:
        return "Error: Received an invalid response from the AI. This usually happens when the server is overloaded. Please try again in a moment."
    except Exception as e:
        return f"Unexpected Error: {str(e)}"

# --- PDF GENERATION ---
def create_pdf(text, year):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, f"UK Historical Summary: {year}", ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("Helvetica", size=11)
    # Cleaning text for PDF compatibility
    clean_text = text.encode('latin-1', 'ignore').decode('latin-1')
    pdf.multi_cell(0, 8, clean_text)
    return pdf.output()

# --- UI ---
st.title("🇬🇧 UK Year Researcher")
st.write("Enter a year to receive a summary of UK historical events.")

target_year = st.number_input("Year to Research:", min_value=1, max_value=2026, value=2024)
st.caption("⚠️ **Disclaimer:** Information is generated by AI. Verify facts with primary sources.")

if st.button("Give Info"):
    with st.spinner(f"Contacting AI for {target_year} data..."):
        prompt = f"Provide a historical summary of the United Kingdom in {target_year}. Focus on Politics, Culture, and Economy. List sources at the end."
        answer = query_ai(prompt)
        st.session_state['summary_text'] = answer
        st.session_state['searched_year'] = target_year

# --- DISPLAY & DOWNLOAD ---
if 'summary_text' in st.session_state:
    st.markdown("---")
    output = st.session_state['summary_text']
    st.markdown(output)
    
    # Only show PDF button if there wasn't an error
    if "Error" not in output and "waking up" not in output:
        try:
            pdf_output = create_pdf(output, st.session_state['searched_year'])
            st.download_button(
                label="📥 Download Research as PDF",
                data=bytes(pdf_output),
                file_name=f"UK_History_{st.session_state['searched_year']}.pdf",
                mime="application/pdf"
            )
        except:
            st.warning("Could not generate PDF for this specific result, but you can copy the text above.")